export const roots = [
	{ root: "ag", definition: "do; act", examples: [] },
	{ root: "agri", definition: "field; farming", examples: [] },
	{ root: "ann", definition: "year", examples: [] },
	{ root: "audi", definition: "hear", examples: [] },
	{ root: "bell", definition: "war", examples: [] },
	{ root: "brev", definition: "short", examples: [] },
	{ root: "ced", definition: "go; yield", examples: [] },
	{ root: "cept", definition: "take; hold", examples: [] },
	{ root: "cid, cis", definition: "cut; kill", examples: [] },
	{ root: "circ", definition: "around", examples: [] },
	{ root: "claim, clam", definition: "shout; cry out", examples: [] },
	{ root: "clar", definition: "clear", examples: [] },
	{ root: "clud", definition: "shut", examples: [] },
	{ root: "cogn", definition: "know", examples: [] },
	{ root: "cord", definition: "heart", examples: [] },
	{ root: "corpor", definition: "body", examples: [] },
	{ root: "cred", definition: "believe", examples: [] },
	{ root: "cruc", definition: "cross", examples: [] },
	{ root: "cur", definition: "run", examples: [] },
	{ root: "cur, curs, cour, ccurs", definition: "run", examples: [] },
	{ root: "dent", definition: "tooth", examples: [] },
	{ root: "di", definition: "two; double", examples: [] },
	{ root: "dict", definition: "say", examples: [] },
	{ root: "dit", definition: "give", examples: [] },
	{ root: "don", definition: "give", examples: [] },
	{ root: "du", definition: "two", examples: [] },
	{ root: "duc", definition: "lead", examples: [] },
	{ root: "ed", definition: "eat", examples: [] },
	{ root: "equ", definition: "equal", examples: [] },
	{ root: "ev", definition: "time; age", examples: [] },
	{ root: "fact", definition: "make; do", examples: [] },
	{ root: "fer", definition: "carry", examples: [] },
	{ root: "flor", definition: "flower", examples: [] },
	{ root: "flu", definition: "flow", examples: [] },
	{ root: "fus", definition: "pour", examples: [] },
	{ root: "grad", definition: "step", examples: [] },
	{ root: "gram", definition: "letter; written", examples: [] },
	{ root: "graph", definition: "write", examples: [] },
	{ root: "gress", definition: "step", examples: [] },
	{ root: "habit", definition: "have; live", examples: [] },
	{ root: "hibit", definition: "hold", examples: [] },
	{ root: "hospit", definition: "guest", examples: [] },
	{ root: "idio", definition: "peculiar; personal", examples: [] },
	{ root: "insul", definition: "island", examples: [] },
	{ root: "it", definition: "go", examples: [] },
	{ root: "ject", definition: "throw", examples: [] },
	{ root: "juven", definition: "young", examples: [] },
	{ root: "lect", definition: "choose; gather", examples: [] },
	{ root: "lev", definition: "light", examples: [] },
	{ root: "liber", definition: "free", examples: [] },
	{ root: "lingu", definition: "tongue; language", examples: [] },
	{ root: "liter", definition: "letter", examples: [] },
	{ root: "loc", definition: "place", examples: [] },
	{ root: "log", definition: "word", examples: [] },
	{ root: "loqu", definition: "speak", examples: [] },
	{ root: "lun", definition: "moon", examples: [] },
	{ root: "man", definition: "hand", examples: [] },
	{ root: "manu", definition: "hand", examples: [] },
	{ root: "mar", definition: "sea", examples: [] },
	{ root: "medi", definition: "middle", examples: [] },
	{ root: "memor", definition: "mindful", examples: [] },
	{ root: "merg", definition: "dip", examples: [] },
	{ root: "migr", definition: "move", examples: [] },
	{ root: "milit", definition: "soldier", examples: [] },
	{ root: "mini", definition: "small", examples: [] },
	{ root: "mir", definition: "wonder", examples: [] },
	{ root: "miss", definition: "send", examples: [] },
	{ root: "mob", definition: "move", examples: [] },
	{ root: "mort", definition: "death", examples: [] },
	{ root: "mot", definition: "move", examples: [] },
	{ root: "nov", definition: "new", examples: [] },
	{ root: "numer", definition: "number", examples: [] },
	{ root: "onym", definition: "name", examples: [] },
	{ root: "oper", definition: "work", examples: [] },
	{ root: "ori", definition: "rise", examples: [] },
	{ root: "paci", definition: "peace", examples: [] },
	{ root: "pel", definition: "drive", examples: [] },
	{ root: "pend", definition: "hang", examples: [] },
	{ root: "pet", definition: "seek", examples: [] },
	{ root: "phon", definition: "sound", examples: [] },
	{ root: "pict", definition: "paint", examples: [] },
	{ root: "plen", definition: "full", examples: [] },
	{ root: "plic", definition: "fold", examples: [] },
	{ root: "pon", definition: "put", examples: [] },
	{ root: "popul", definition: "people", examples: [] },
	{ root: "port", definition: "carry", examples: [] },
	{ root: "pos", definition: "put", examples: [] },
	{ root: "preci", definition: "value", examples: [] },
	{ root: "punct", definition: "point", examples: [] },
	{ root: "pur", definition: "cleanse", examples: [] },
	{ root: "rect", definition: "right", examples: [] },
	{ root: "rupt", definition: "break", examples: [] },
	{ root: "sal", definition: "salt", examples: [] },
	{ root: "scend", definition: "climb", examples: [] },
	{ root: "sci", definition: "know", examples: [] },
	{ root: "sect", definition: "cut", examples: [] },
	{ root: "sent", definition: "feel", examples: [] },
	{ root: "sid", definition: "sit", examples: [] },
	{ root: "sist", definition: "stand", examples: [] },
	{ root: "son", definition: "sound", examples: [] },
	{ root: "spect", definition: "look", examples: [] },
	{ root: "spir", definition: "breathe", examples: [] },
	{ root: "tain, tan, tin", definition: "hold", examples: [] },
	{ root: "tect", definition: "cover", examples: [] },
	{ root: "tele", definition: "far", examples: [] },
	{ root: "tempor", definition: "time", examples: [] },
	{ root: "tend", definition: "stretch", examples: [] },
	{ root: "terr", definition: "earth", examples: [] },
	{ root: "text", definition: "weave", examples: [] },
	{ root: "tract", definition: "pull", examples: [] },
	{ root: "un", definition: "not", examples: [] },
	{ root: "urb", definition: "city", examples: [] },
	{ root: "vac", definition: "empty", examples: [] },
	{ root: "vad", definition: "go", examples: [] },
	{ root: "vari", definition: "different", examples: [] },
	{ root: "ven", definition: "come", examples: [] },
	{ root: "vert", definition: "turn", examples: [] },
	{ root: "vi, via", definition: "way", examples: [] },
	{ root: "vis", definition: "see", examples: [] },
	{ root: "vit", definition: "life", examples: [] },
	{ root: "viv", definition: "life", examples: [] },
	{ root: "aer(o)", definition: "air", examples: [] },
	{ root: "alt", definition: "high", examples: [] },
	{ root: "am", definition: "love", examples: [] },
	{ root: "ambul", definition: "walk", examples: [] },
	{ root: "anim", definition: "life, spirit", examples: [] },
	{ root: "anthrop(o)", definition: "man, human", examples: [] },
	{ root: "aqu", definition: "water", examples: [] },
	{ root: "arch", definition: "chief, ruler", examples: [] },
	{ root: "avi", definition: "bird", examples: [] },
	{ root: "bat", definition: "beat", examples: [] },
	{ root: "biblio", definition: "book", examples: [] },
	{ root: "brig", definition: "fight", examples: [] },
	{ root: "cad, cas", definition: "fall", examples: [] },
	{ root: "cert", definition: "sure", examples: [] },
	{ root: "chron", definition: "time", examples: [] },
	{ root: "cid", definition: "fall", examples: [] },
	{ root: "clin", definition: "lean", examples: [] },
	{ root: "cosm(o)", definition: "universe", examples: [] },
	{ root: "cracy", definition: "rule", examples: [] },
	{ root: "cub", definition: "lie down", examples: [] },
	{ root: "cult", definition: "till", examples: [] },
	{ root: "cycl(c)", definition: "circle", examples: [] },
	{ root: "dem(o)", definition: "people", examples: [] },
	{ root: "dexter", definition: "right", examples: [] },
	{ root: "doc", definition: "teach", examples: [] },
	{ root: "dom", definition: "home", examples: [] },
	{ root: "dorm", definition: "sleep", examples: [] },
	{ root: "drom", definition: "run", examples: [] },
	{ root: "ego", definition: "I", examples: [] },
	{ root: "err", definition: "wander", examples: [] },
	{ root: "fabl, fabul", definition: "speak", examples: [] },
	{ root: "feder", definition: "league", examples: [] },
	{ root: "ferv", definition: "boil", examples: [] },
	{ root: "fict, fig", definition: "form", examples: [] },
	{ root: "fid", definition: "trust", examples: [] },
	{ root: "fil", definition: "thread", examples: [] },
	{ root: "flat", definition: "blow", examples: [] },
	{ root: "flect, flex", definition: "bend", examples: [] },
	{ root: "flict", definition: "strike", examples: [] },
	{ root: "frag, fract", definition: "break", examples: [] },
	{ root: "frig", definition: "cold", examples: [] },
	{ root: "fug", definition: "flee", examples: [] },
	{ root: "fund, found", definition: "bottom", examples: [] },
	{ root: "gam", definition: "marriage", examples: [] },
	{ root: "gran", definition: "grain", examples: [] },
	{ root: "grav", definition: "heavy", examples: [] },
	{ root: "greg", definition: "flock", examples: [] },
	{ root: "gyn, gynec(o)", definition: "woman", examples: [] },
	{ root: "hal", definition: "breathe", examples: [] },
	{ root: "helic(o)", definition: "spiral", examples: [] },
	{ root: "hes, her", definition: "stick", examples: [] },
	{ root: "ign", definition: "fire", examples: [] },
	{ root: "integr", definition: "whole", examples: [] },
	{ root: "junct", definition: "join", examples: [] },
	{ root: "later", definition: "side", examples: [] },
	{ root: "leg", definition: "read", examples: [] },
	{ root: "leg", definition: "law", examples: [] },
	{ root: "luc", definition: "light", examples: [] },
	{ root: "lumin", definition: "light", examples: [] },
	{ root: "magn(i)", definition: "large", examples: [] },
	{ root: "matr(i), metro", definition: "mother", examples: [] },
	{ root: "mega", definition: "great", examples: [] },
	{ root: "mens", definition: "measure", examples: [] },
	{ root: "ment", definition: "mind", examples: [] },
	{ root: "min", definition: "project", examples: [] },
	{ root: "misc", definition: "mix", examples: [] },
	{ root: "mis(o)", definition: "hate", examples: [] },
	{ root: "mon", definition: "warn", examples: [] },
	{ root: "mon", definition: "one", examples: [] },
	{ root: "mur", definition: "wall", examples: [] },
	{ root: "mut", definition: "change", examples: [] },
	{ root: "nat", definition: "born", examples: [] },
	{ root: "nav", definition: "ship", examples: [] },
	{ root: "nect, nex", definition: "tie", examples: [] },
	{ root: "negr, nigr", definition: "black", examples: [] },
	{ root: "nihil", definition: "nothing", examples: [] },
	{ root: "noc, nox", definition: "harm", examples: [] },
	{ root: "noct(i)", definition: "night", examples: [] },
	{ root: "norm", definition: "rule", examples: [] },
	{ root: "nutri", definition: "nourish", examples: [] },
	{ root: "orn", definition: "decorate", examples: [] },
	{ root: "par", definition: "bear", examples: [] },
	{ root: "parl", definition: "speak", examples: [] },
	{ root: "past", definition: "feed", examples: [] },
	{ root: "paht(o), pathy", definition: "disease", examples: [] },
	{ root: "patr(i)", definition: "father", examples: [] },
	{ root: "ped", definition: "foot", examples: [] },
	{ root: "ped", definition: "child", examples: [] },
	{ root: "petr(o)", definition: "stone", examples: [] },
	{ root: "phag", definition: "eat", examples: [] },
	{ root: "phil(o)", definition: "love", examples: [] },
	{ root: "phob(ia)", definition: "fear", examples: [] },
	{ root: "plex", definition: "weave", examples: [] },
	{ root: "polis", definition: "city", examples: [] },
	{ root: "prim", definition: "first", examples: [] },
	{ root: "radic", definition: "root", examples: [] },
	{ root: "ras, rad", definition: "scrape", examples: [] },
	{ root: "rid, ris", definition: "laugh", examples: [] },
	{ root: "rod, ros", definition: "gnaw", examples: [] },
	{ root: "rot", definition: "wheel", examples: [] },
	{ root: "rud", definition: "rough", examples: [] },
	{ root: "rur, rus", definition: "country", examples: [] },
	{ root: "sat, satis, satur", definition: "full", examples: [] },
	{ root: "sen", definition: "old", examples: [] },
	{ root: "simil, simul", definition: "same", examples: [] },
	{ root: "sol", definition: "alone", examples: [] },
	{ root: "sol", definition: "sun", examples: [] },
	{ root: "soph", definition: "wise", examples: [] },
	{ root: "sper", definition: "hope", examples: [] },
	{ root: "spers, spars", definition: "scatter", examples: [] },
	{ root: "splend", definition: "shine", examples: [] },
	{ root: "stell", definition: "star", examples: [] },
	{ root: "tact, tag", definition: "touch", examples: [] },
	{ root: "the(o)", definition: "god", examples: [] },
	{ root: "ton", definition: "sound", examples: [] },
	{ root: "tort", definition: "twist", examples: [] },
	{ root: "tour", definition: "turn", examples: [] },
	{ root: "trud, trus", definition: "push", examples: [] },
	{ root: "tut, tuit", definition: "guard", examples: [] },
	{ root: "umbr", definition: "shade", examples: [] },
	{ root: "ut, us", definition: "use", examples: [] },
	{ root: "vag", definition: "wander", examples: [] },
	{ root: "val", definition: "strong", examples: [] },
	{ root: "van", definition: "empty", examples: [] },
	{ root: "ver(i)", definition: "true", examples: [] },
	{ root: "voc, vok", definition: "call", examples: [] },
	{ root: "vol, volunt", definition: "will", examples: [] },
	{ root: "volu, volv", definition: "roll", examples: [] },
];
