export const prefixes = [
	{ prefix: "anti", definition: "against", examples: ["anticlimax"] },
	{ prefix: "de", definition: "opposite", examples: ["devalue"] },
	{
		prefix: "dis",
		definition: "not; opposite of",
		examples: ["discover"],
	},
	{ prefix: "en", definition: "cause to", examples: ["enact"] },
	{ prefix: "em", definition: "cause to", examples: ["empower"] },
	{
		prefix: "fore",
		definition: "before; front of",
		examples: ["foreshadow", "forearm"],
	},
	{ prefix: "in", definition: "in", examples: ["income", "impulse"] },
	{ prefix: "im", definition: "in", examples: ["impulse"] },
	{ prefix: "in", definition: "not", examples: ["indirect"] },
	{ prefix: "im", definition: "not", examples: ["immoral"] },
	{ prefix: "il", definition: "not", examples: ["illiterate"] },
	{ prefix: "ir", definition: "not", examples: ["irreverent"] },
	{
		prefix: "inter",
		definition: "between; among",
		examples: ["interrupt"],
	},
	{ prefix: "mid", definition: "middle", examples: ["midfield"] },
	{ prefix: "mis", definition: "wrongly", examples: ["misspell"] },
	{ prefix: "non", definition: "not", examples: ["nonviolent"] },
	{ prefix: "over", definition: "over; too much", examples: ["overeat"] },
	{ prefix: "pre", definition: "before", examples: ["preview"] },
	{ prefix: "re", definition: "again", examples: ["rewrite"] },
	{
		prefix: "semi",
		definition: "half; partly; not fully",
		examples: ["semifinal"],
	},
	{ prefix: "sub", definition: "under", examples: ["subway"] },
	{
		prefix: "super",
		definition: "above; beyond",
		examples: ["superhuman"],
	},
	{ prefix: "trans", definition: "across", examples: ["transmit"] },
	{ prefix: "un", definition: "not; opposite of", examples: ["unusual"] },
	{
		prefix: "under",
		definition: "under; too little",
		examples: ["underestimate"],
	},
];
